name: New laboratory instrument layout
description: Describe a laboratory instrument
title: "[Instrument Layout]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: >
        # Introduction
        
        Please fill in as much of the following information as possible. This form is not suitable for multi-detector setups. To add a multi-detector setup, please create a
        free-form Github issue.
  - type: dropdown
    id: manufacturer
    attributes:
      label: Name of manufacturer
      options:
        - Agilent
        - Anton Paar
        - Bruker
        - Liaodong
        - PANalytical
        - Rigaku
        - Stoe 
        - Other (please write name in the comments at end of form)
  - type: input
    id: model
    attributes:
      label: Model
      description: Please give the manufacturer model name.
  - type: input
    id: extra
    attributes:
      label: Location
      description: >
        If geometry and/or detector varies for the same manufacturer and model, please provide the location of the
        instrument, for example, "University of Wessex Crystallography Lab"
  - type: markdown
    attributes:
      value: >
        ## Goniometer information
      
        Answer the following questions for all axes in zero position.
  - type: input
    id: gonio
    attributes:
      label: Principal axis orientation
      description: > 
        With all angles at zero, and looking along the beam towards the detector, imagine an arrow drawn from the sample to the 
        centre of the goniometer base.
        At what angle in degrees is this arrow to the horizontal plane, where 0 is '3 o'clock' and angles are measured counter-clockwise,
        so 90 is 12 o'clock and 270 is 6 o'clock.
  - type: input
    id: axis_stack
    attributes:
      label: Goniometer axes
      description: >
        For each axis attached to the goniometer, give the axis name (as used in data files if known) and
        sense of rotation (a=anticlockwise, c=clockwise) when looking from the crystal in the direction of the goniometer. Separate
        each value by a comma, for example 'Chi, c, Omega, a'. See the instructions for &#967; below for correct description
        of the &#967; direction of rotation. List the axes in order of stacking from
        closest to the crystal to furthest (`phi` would typically be first if present, `omega` is usually last).
  - type: input
    id: &#954;
    attributes:
      label: kappa
      description: >
        If your goniometer has a &#954; axis, please give its name and &#954; angle here, for example "kappa 50". When looking
        from above, with the beam going from left to right and all axes at their zero positions, the &#954; base is assumed to
        be at the left. If this is not the case, please append the base location as a counter-clockwise rotation from this 
        position when looking from above. For example, if the &#954; base is located on the detector side, type "kappa 50 180".
  - type: input
    id: chi
    attributes:
      label: &#967;
      description: >
        If your goniometer has a &#967; axis, please give its name here, followed by an &#969; angle at which the &#967; rotation
        axis is parallel to the beam. The sense of rotation provided for &#967; in the "Goniometer axes" question above is the
        sense of rotation when the &#969; axis has been rotated by this angle and the &#967; axis is viewed from the beam direction.
        For example, if &#969; is rotated by 90 to bring the &#967; axis parallel to the beam and moving to positive &#967; rotates the crystal
        anticlockwise when viewed from the source, `chi,a` should be given for "Goniometer axes" and `chi 90` should be provided 
        here. `chi,c` with `chi -90` would also describe the same situation.
  - type: markdown
    attributes:
      value: >
        ## Detector information
        
        Answer the following questions assuming all detector positioning axes are at their home positions. If there is more
        than one detector, or detectors
        are non-rectangular, please describe in the comments below.
  - type: dropdown
    attributes:
      label: Image orientation
      description: >
        The first pixel of the raw image is located at what position on the detector when viewing the detector from the crystal
        position?
      options:
        - top left
        - top right
        - bottom left
        - bottom right
        - other (please describe in comments)
  - type: dropdown
    attributes:
      label: Fast direction
      description: >
        The second pixel of the raw image is located in what direction relative to the first pixel?
      options:
        - horizontal
        - vertical
  - type: input
    id: pixsize
    attributes:
      label: Pixel size
      description: >
         The size of pixels in mm in order horizontal, vertical (eg '0.12, 0.15'). If identical sizes, a single number is sufficient. 
         Pixels are assumed to have no space between them, if this is not the case please write in the comments section below.
  - type: input
    id: two_theta
    attributes:
      label: Two theta axis
      description: >
        When looking from above, what is the sense of rotation of the two theta axis?
  - type: textarea
    id: det_axis_stack
    attributes:
      label: Other detector axes
      description: >
        If the detector is repositioned during data collection (excluding distance from the
        sample and two theta), please name the repositioning axes as they appear in data files, classify the
        axes as rotation or translation, and
        explain their relationship to one another.
  - type: textarea
    id: xds
    attributes:
      label: xds.inp
      description: >-
        If XDS is used to reduce data from this configuration, please attach an `XDS.INP`
        file here.
  - type: input
    id: doi
    attributes:
      label: Data DOI
      description: >-
        If available, please give the DOI of a raw data set obtained using this configuration
        that includes images separated by at least 90 degrees of phi rotation.
        Consider uploading a representative data set to Zenodo if automated public access is not otherwise
        available for your instrument. These data will be used (in future) for automated checking
        of the configuration.
  - type: textarea
    attributes:
      label: Comments
      description: >
        Please provide any additional comments.
        
        
        
        
      
