name: New beamline layout
description: Describe a new beamline layout
title: "[Layout]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        # Introduction
        
        Please fill in as much of the following information as possible. This form is not suitable for multi-detector setups. To add a multi-detector setup, please create a
        free-form Github issue.
  - type: dropdown
    id: facility
    attributes:
      label: Facility name
      options:
        - APS
        - Spring-8
        - KEK-PF
        - Australian Synchrotron
        - J-PARC
        - ESRF
        - ILL
        - Oak Ridge
        - Diamond
        - ESS
        - ANKA
        - KAERI
        - Other (please write name in the comments at end of form)
  - type: input
    id: beamline
    attributes:
      label: Beamline name
      description: Please type the beamline name, without hyphens.
  - type: checkboxes
    id: is-update
    attributes:
      label: Is updated?
      description: Is this an update to an existing specification?
      options:
        - label: Is an update
  - type: input
    id: early-date
    attributes:
      label: Start date
      description: Earliest known date that this beamline setup is possible, if known (YYYY-MM-DD)
  - type: input
    id: last-date
    attributes:
      label: Finish date
      description: Last known date for this configuration (YYYY-MM-DD), blank if unknown
  - type: markdown
    attributes:
      value: >
        ## Goniometer information
      
        Answer the following questions for all axes in zero position.
  - type: input
    id: gonio
    attributes:
      label: Principal axis orientation
      description: > 
        With all angles at zero, and looking along the beam towards the detector, imagine an arrow drawn from the sample to the 
        centre of the goniometer base.
        At what angle in degrees is this arrow to the horizontal plane, where 0 is '3 o'clock' and angles are measured counter-clockwise,
        so 90 is 12 o'clock and 270 is 6 o'clock.
  - type: input
    id: axis_stack
    attributes:
      label: Goniometer axes
      description: >
        For each axis attached to the goniometer, give the axis name (as used in data files if known) and
        sense of rotation (a=anticlockwise, c=clockwise) when looking from the crystal in the direction of the goniometer. Separate
        each value by a comma, for example 'Chi, c, Omega, a'. List the axes in order of stacking from
        closest to the crystal to furthest (phi would typically be first if present, omega is usually last).
  - type: input
    id: gonio_rot
    attributes:
      label: Rotation axis name
      description: "Of the axes listed in the previous question, which one is the rotation axis used for data collection?"
  - type: input
    id: kappa
    attributes:
      label: kappa
      description: >
        If your goniometer has a kappa axis, please give its name and kappa angle here, for example "kappa 50"
  - type: markdown
    attributes:
      value: >
        ## Detector information
        
        Answer the following questions assuming all detector positioning axes are at their home positions. If there is more
        than one detector, or detectors
        are non-rectangular, please describe in the comments below.
  - type: dropdown
    attributes:
      label: Image orientation
      description: >
        The first pixel of the raw image is located at what position on the detector when viewing the detector from the crystal
        position?
      options:
        - top left
        - top right
        - bottom left
        - bottom right
        - other (please describe in comments)
  - type: dropdown
    attributes:
      label: Fast direction
      description: >
        The second pixel of the raw image is located in what direction relative to the first pixel?
      options:
        - horizontal
        - vertical
  - type: textarea
    id: det_axis_stack
    attributes:
      label: Detector axes
      description: >
        If the detector is repositioned during data collection (excluding distance from the
        sample), please name the repositioning axes as they appear in data files, classify the
        axes as rotation or translation, and
        explain their relationship to one another.
  - type: textarea
    id: xds
    attributes:
      label: xds.inp
      description: >-
        If XDS is used to reduce data from this configuration, please attach an `XDS.INP`
        file here.
  - type: input
    id: doi
    attributes:
      label: Data DOI
      description: >-
        If available, please give the DOI of a raw data set obtained using this configuration
        that includes images separated by at least 90 degrees of phi rotation.
        Consider uploading a representative data set to Zenodo if automated public access is not otherwise
        available for your instrument. These will be used in future for automated checking
        of the configuration.
  - type: textarea
    attributes:
      label: Comments
      description: >
        Please provide any additional comments.
        
        
        
        
      
